### ISSUE TITLE
Personalities files case sensitive

### ISSUE THREAD

**Issue by ghost** [nescitus/Rodent_II#32]
Here at linux files are case sensitive. Currently personalities file sometimes start with a capital (mostly Chess players) and playing style with small letters. 

I suggest to start all files with a small letter or a capital as you like it. But all in the same style.

**Comment by nescitus** [comment]
Good suggestion but GitHub is case insensitive and so my commit failed. I'll think about it tomorrow

**Comment by nescitus** [comment]
changed to lowercase
