### ISSUE TITLE
Remy personality wrong OwnAttack

### ISSUE THREAD

**Issue by covrom** [nescitus/Rodent_II#38]
In remy.txt OwnAttack=100 and OppAttack=400 is wrong?

**Comment by LocutusOfPenguin** [comment]
also some "MobilityStyle" is wrong over various files

next errors:
Mark & Steinitz => missing GuideBookFile

**Comment by nescitus** [comment]
Henny personality fixed. What is wrong with MobilityStyle?

2016-12-02 14:33 GMT+01:00 Jürgen Précour <notifications@github.com>:

**Comment by LocutusOfPenguin** [comment]
look for "steoption"  .. many places for example here: famous/larsen.txt

BTW. there are not all guide books inside (from the personality files) for example: guide/mini.bin

**Comment by nescitus** [comment]
thanks, "steoptions" fixed!

2016-12-06 20:52 GMT+01:00 Jürgen Précour <notifications@github.com>:
